Age_1 = input("Enter a number: ")
Name_1 = input("Enter a Person's Name: ")
animal_1 = input("Enter an animal: ")
verb_1 = input("Enter a verb or action like 'walk' or 'eat': ")
place_1 = input("Enter a place: ")
noun_1 = input("Enter a noun or a thing: ")
plural_noun_1 = input("Enter a plural noun, like 'bananas': ")
color_1 = input("Enter a color: ")
verb_2 = input("Enter a verb or action like 'walking' or 'eating': ")
famous_person = input("Enter a famous person: ")
verb_3 = input("Enter a verb or action like 'walking' or 'eating': ")
adjective_1 = input("Enter an adjective like 'big' or 'small' or 'hot' or 'cold': ")
print("Hi, my name is "+ Name_1 + ".  I am " + Age_1 + " years old.")
print("I have a pet " + animal_1 + " who loved to " + verb_1)
print("Once, I took my pet " + animal_1 + " to the " + place_1 + " to see the " + noun_1)
print("At the " + place_1 + " lots of people came to see the " + color_1 + " " + plural_noun_1 + ".")
print("The " + color_1  + " " +  plural_noun_1 + " were " + verb_2 + " and the people were very surprised to see " + famous_person + " there too! ")
print("Suddenly " + famous_person + " started " + verb_3 + " all around and the " + plural_noun_1 + " also joined in!  It was very " + adjective_1 + "!")
